"""P1. Audit the raw table. Audit, don't delete: duplicates and repeated timestamps are KEPT."""
import json
from pathlib import Path
import pandas as pd


def audit(df: pd.DataFrame) -> dict:
    feats = df.drop(columns="txn_id")
    d = df["ts"].diff().dt.total_seconds()
    fx = df["cur_paid"].astype(str) != df["cur_recv"].astype(str)
    amt = df["amount_paid"]
    dup_mask = feats.duplicated(keep="first")
    return {
        "n_rows": int(len(df)),
        "n_positives": int(df["is_laundering"].sum()),
        "positive_rate": float(df["is_laundering"].mean()),
        "nulls": {c: int(v) for c, v in df.isna().sum().items()},
        "ts_min": str(df["ts"].min()), "ts_max": str(df["ts"].max()),
        "n_distinct_timestamps": int(df["ts"].nunique()),
        "raw_is_chronological": bool(df["ts"].is_monotonic_increasing),
        "rows_stepping_backwards_in_time": int((d < 0).sum()),
        "exact_duplicate_extra_rows": int(dup_mask.sum()),
        "exact_duplicate_extra_rows_laundering": int(df.loc[dup_mask, "is_laundering"].sum()),
        "currencies": sorted(set(df["cur_paid"].astype(str)) | set(df["cur_recv"].astype(str))),
        "payment_formats": sorted(df["payment_format"].astype(str).unique()),
        "amount_paid_min": float(amt.min()), "amount_paid_max": float(amt.max()),
        "amount_paid_nonpositive": int((amt <= 0).sum()),
        "amount_paid_le_0.01": int((amt <= 0.01).sum()),
        "fx_rows": int(fx.sum()),
        "fx_rows_positive": int(df.loc[fx, "is_laundering"].sum()),
        "non_fx_rows_with_unequal_amounts": int(((~fx) & (df["amount_paid"] != df["amount_received"])).sum()),
        "bank_codes_have_leading_zeros": bool(df["from_bank"].astype(str).str.startswith("0").any()),
    }


def check_expectations(rep: dict, cfg: dict) -> list[str]:
    """Return a list of problems (empty = OK). Fails loudly on wrong/modified dataset."""
    ds, bad = cfg["dataset"], []
    if rep["n_rows"] != ds["expected_rows"]:
        bad.append(f"rows {rep['n_rows']} != {ds['expected_rows']}")
    if rep["n_positives"] != ds["expected_positives"]:
        bad.append(f"positives {rep['n_positives']} != {ds['expected_positives']}")
    if rep["exact_duplicate_extra_rows"] != ds["expected_exact_duplicates"]:
        bad.append(f"duplicates {rep['exact_duplicate_extra_rows']} != {ds['expected_exact_duplicates']}")
    if any(rep["nulls"].values()):
        bad.append(f"unexpected nulls: {rep['nulls']}")
    if rep["amount_paid_nonpositive"] != 0:
        bad.append("non-positive amounts found")
    return bad


def write_report(rep: dict, out_json: Path, out_md: Path) -> None:
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(rep, indent=2))
    lines = ["# Data quality audit (auto-generated by `scripts/run_data.py`)", ""]
    lines += [f"- **{k}**: {v}" for k, v in rep.items() if k != "nulls"]
    lines += ["", f"- **nulls**: {rep['nulls']}", "",
              "Policy: exact duplicates are audited but NOT deleted (no reliable transaction ID); "
              "repeated timestamps are normal. See `docs/data_contract.md`."]
    out_md.write_text("\n".join(lines))
